
// try catch

try{
    throw new Error('This a new error')
} catch(error){
    console.log('the error message is '+ error)
}
